### PR TITLE
Looking forward to getting feedback from code review.

### PR DESCRIPTION
**Pull request by FuePi**
- Added proxy support.
- Added multiple team support.
- Fixed a mechanize download error.
- Added profile verification against Apple's root certificate.
- Refactored option parsing and variable naming.

### CODE REVIEW

**Comment by jcollas** [comment]
This is exactly what I was looking for, thank you.  It's working perfectly.  Would it make sense for -t (team) argument to also support the team display name in addition to the team id?

**Comment by FuePi** [comment]
Thank you both for your feedback.

@jcollas 
I'll add the team name option.

@lacostej 
Sorry for stuffing all changes in one commit and forgetting to update the README. 

We build iPad apps with Jenkins for OTA distribution. 
Every time the provisioning profile changes we have to manually download it and start the build.
With your scripts we automated this step too :)

**Comment by lacostej** [comment]
@FuePi I wrote the scripts for the exact same reasons.

I've noticed yesterday that a few more people forked the scripts and added some interesting features (like add device ID, etc), but I received no pull request. If you need more features, you might want to look into those forks they may already have done it.

**Comment by lacostej** [comment]
I will of course merge everything that is being sent to me :)

**Pull request merged**
